skip-check:
  - CKV_AWS_150
  - CKV_AWS_260
  - CKV_AWS_356
  - CKV_AWS_111
  - CKV_AWS_109
  - CKV2_AWS_62
  - CKV2_AWS_38
  - CKV_AWS_144
  - CKV2_AWS_39
  - CKV_AWS_145
  - CKV_AWS_18
  - CKV2_AWS_28