name: Docker Build and Push

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: en-automotive-app

jobs:
  build-and-push:
    name: Build and push to ECR

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    steps:
      - name: Check out successful commit
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
        run: |
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

          echo "Building $IMAGE_URI"

          docker build -t "$IMAGE_URI" ./app
          docker push "$IMAGE_URI"

          echo "Successfully pushed $IMAGE_URI"